spring.application.name=atendimento-pacientes-crud

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/atendimento_pacientes_crud}
spring.datasource.username=${DB_USERNAME:atendimento_user}
spring.datasource.password=${DB_PASSWORD:152518}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.datasource.hikari.initialization-fail-timeout=0

# Web / JSF
server.port=8080
joinfaces.faces.project-stage=Development
joinfaces.faces-servlet.url-mappings=*.xhtml
