spring.application.name=atendimento-pacientes-crud

# Configuracao inicial do PostgreSQL.
# Ajuste usuario, senha e banco antes de executar com persistencia real.
spring.datasource.url=jdbc:postgresql://localhost:5432/atendimento_pacientes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.datasource.hikari.initialization-fail-timeout=0

server.port=8080
joinfaces.faces.project-stage=Development
joinfaces.faces-servlet.url-mappings=*.xhtml
